language: node_js
notifications:
  email: false
after_install: npm ls >/dev/null
script: npm test
after_success: npm run coverage:report
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
